{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Table\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.134.0.0 (Main)+e81ccb5a27c105f5dd3551e6977a4fbd21ac139c"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Table",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Administrative",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eef67871-91c1-4979-8939-9bed97d706b7",
            "sourceColumn": "Administrative",
            "summarizeBy": "sum"
          },
          {
            "name": "Administrative_Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e7de3aff-dc49-4527-a8db-a40ff1f440d0",
            "sourceColumn": "Administrative_Duration",
            "summarizeBy": "sum"
          },
          {
            "name": "Informational",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "978b60cc-39da-40c4-b8a1-fc45d3a3b93a",
            "sourceColumn": "Informational",
            "summarizeBy": "sum"
          },
          {
            "name": "Informational_Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "eed5c9b4-5488-4fde-b6f9-d8610779a000",
            "sourceColumn": "Informational_Duration",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductRelated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d083cea9-ed65-4e08-8a06-8d45752dc1b5",
            "sourceColumn": "ProductRelated",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductRelated_Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "243f3374-6ff6-4368-acf9-dd59174d9c0b",
            "sourceColumn": "ProductRelated_Duration",
            "summarizeBy": "sum"
          },
          {
            "name": "BounceRates",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8c55875d-dec7-4bb2-b1ec-b82222e5f085",
            "sourceColumn": "BounceRates",
            "summarizeBy": "sum"
          },
          {
            "name": "ExitRates",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4790eb80-520a-44f1-9e29-c76d043fe33d",
            "sourceColumn": "ExitRates",
            "summarizeBy": "sum"
          },
          {
            "name": "PageValues",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "94c8071b-2721-426c-9125-7fcbde363df8",
            "sourceColumn": "PageValues",
            "summarizeBy": "sum"
          },
          {
            "name": "SpecialDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "81caec72-43ef-4ad7-98a0-46f51907cdca",
            "sourceColumn": "SpecialDay",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da4918d9-c0dc-43e9-8e46-0f959308e59c",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "OperatingSystems",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2124f52b-5865-4b0a-a0bc-46e9ef0b16b9",
            "sourceColumn": "OperatingSystems",
            "summarizeBy": "sum"
          },
          {
            "name": "Browser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "71cb2d38-e4c1-405e-bd80-3f930ace3eb4",
            "sourceColumn": "Browser",
            "summarizeBy": "sum"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "563c332a-2af3-415b-9d5a-16018c27d4b4",
            "sourceColumn": "Region",
            "summarizeBy": "sum"
          },
          {
            "name": "TrafficType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c0af3a7b-286b-4e7f-a3aa-5465817f3101",
            "sourceColumn": "TrafficType",
            "summarizeBy": "sum"
          },
          {
            "name": "VisitorType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e63dd977-8a8f-4a19-a0dd-1dcbef24c82a",
            "sourceColumn": "VisitorType",
            "summarizeBy": "none"
          },
          {
            "name": "Weekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d1e6e42b-305c-46e5-baf5-f8a196f90344",
            "sourceColumn": "Weekend",
            "summarizeBy": "none"
          },
          {
            "name": "Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51103453-332d-40bb-9878-2bc6962bb7c5",
            "sourceColumn": "Revenue",
            "summarizeBy": "none"
          },
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "[Month]",
            "isDataTypeInferred": true,
            "lineageTag": "2526ca66-0383-4e5a-8b20-a1623d31710a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "b063d690-86e0-4c13-af98-e3ad841572d0",
        "partitions": [
          {
            "name": "Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"tVhLb9QwEP4ve0bWzHg8to9IwKn0wOtSIQSoQr0UqRT4+4wn9sZu9pFNRbrOJpvE3zw+fzPpzc0Ody92oIPKQHQU9ACZdc9C0XHKIdpNDgC9QLBrekYgwuDbBGVc//zTpiqz1O93t4+/H+7v7n98+XT36+7x54P+9ubl1fvX5YmPV1e7zy9udrE8EMB5RWPK9fHyTVSOENljMYEqPOovKWeqxmAGRrDnXEjE0WPghVnhjFkf3n0crPLlftFdOUhiNpbHY/QuNMcdlKsxuYQYKVCsF17dft8ajRbQNsqUEYJL3rbqc9rHSs+mE7MRBgPM54LO1Yo1jh8ygJAGp/1szBBo33mMWwGNZWLRLsn2Uv5q6qcTv3S1eehPeLqItd0MMLtWeDetguCdUjylSjJlGQSSGn6kKDj6P2a8xeH69u8luRYjWD4Z6AkIOyCEjYGuq4uSLpsepQQd2HNMBcFJCgyQ8D+QO1msfcVv0eWJ3tNZn5tRZC5KtYlMVpGrXJHAbg6uSRkSsBNQz6sh6nTgCNhi4pk4TzFzmQByJamOt18fOsviJTExi2LnpTcpixoWL7rtL6kJokJHodBENSd7Tj4IDib4J6twU1qMUTSvMhUckcGWhct4CV5JQCTuJrMpQsd8SAso7qDi5YvLLN1jOlzMT3UFXsToZJGKJiGmQWzUtCgGyU6o001dRPaxiy6lDCplNBjRwFsJXFuqRNwBsTB+Kmv76lGpRP3CGnMpdazWUKKeGDYFzVAHkIY6sVa+LDQL7yTI1LksymJ/tohxGelEos9qZ5lWcEp8Sa2kLCHUcoFZJXOwdYzwSdk+ymR7MjfHiTtmTeksupSDQvNB1FYft/hrGYMZUM4JwikBOgtmK8THVnzVo/KprqZcPsu0bqpIpr69Flih8I1CdZvOwrTJQeRQF81aQpkGNkmTqe3lsg/A5DgkCNUI8ClqrUn1LCqv0biFSStEAq1JsjDn2aXZ1B9RdSWSYKfMxjR2IecBFLuxlmRUOUseouS92Rb9ZK0g5Oyij741+9rpY4TWh2lLFrNYZFBUT0G0JPvBrF5p1qamp4NZsasdQo3AceU0pNV6NpVa7e0XS8mCr+9k6DxjvVScLz0ZSV0HzJmivenofeyzhiY3097cfmvUei4RZsdp3g8w+GScgpm+j9VnOVyfZ2/W0vo4zHl32qtEPsHkde6Qk14nK3Mc8gKz0bS1pxt9K7vy6t7q4ZKvM1xrn4/BVbqeQJtKETvCzkUMMWWO7T8FrA3qXI8OJ3N7kI8m0/GAxJ3P65CeagAcQxpWQfMobI2plfi545/9S4vItT5iW+Ts/xZ+32SPpe5IBJ+38Cz+uetZDrQQo55clrEFN4ryMUQX941DO6LuffOJrw2b12N//gc=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Administrative = _t, Administrative_Duration = _t, Informational = _t, Informational_Duration = _t, ProductRelated = _t, ProductRelated_Duration = _t, BounceRates = _t, ExitRates = _t, PageValues = _t, SpecialDay = _t, Month = _t, OperatingSystems = _t, Browser = _t, Region = _t, TrafficType = _t, VisitorType = _t, Weekend = _t, Revenue = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Administrative\", Int64.Type}, {\"Administrative_Duration\", type number}, {\"Informational\", Int64.Type}, {\"Informational_Duration\", type number}, {\"ProductRelated\", Int64.Type}, {\"ProductRelated_Duration\", type number}, {\"BounceRates\", type number}, {\"ExitRates\", type number}, {\"PageValues\", type number}, {\"SpecialDay\", type number}, {\"Month\", type text}, {\"OperatingSystems\", Int64.Type}, {\"Browser\", Int64.Type}, {\"Region\", Int64.Type}, {\"TrafficType\", Int64.Type}, {\"VisitorType\", type text}, {\"Weekend\", type logical}, {\"Revenue\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_822483ac-d401-40d6-807a-4f8a53cfb8c5",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b125b231-d8c5-402d-b82d-eb500880990c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "48a50823-1e28-47de-8025-54a39b996c50",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6f9dda45-e926-4cba-8d25-358ae075fcae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "dbef0156-98a2-4855-bfe4-40aed8cda259",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "811448bd-f41f-4b17-92c4-ce4667d1d585",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "518d9969-76d2-4644-bc95-a7482899aaaf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "95b8b4d9-34b8-4f6f-93c4-c47d4a406b74",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "86c23888-5590-4f90-b30a-656660611e2c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e7eb4637-4461-4833-91e1-9bab4922e223",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "60bd8bff-3409-4b8b-af0c-3ec91969bcb3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "fab8229b-8a4d-460d-98ba-81c9a8e40264",
                "ordinal": 3
              }
            ],
            "lineageTag": "bdac5555-e301-4504-aadc-7c39f5bf8434"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "77dbc1bf-aeed-499f-ab9e-093e69a51f1a",
        "partitions": [
          {
            "name": "DateTableTemplate_822483ac-d401-40d6-807a-4f8a53cfb8c5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}