{
  "compatibilityLevel": 1520,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.80.5803.421 (20.04)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "Table1NoParams.RefreshConnections_V0.ServerName.MaxId.BinParam.AnyParam.DateParam.StrParam.BoolParam.DurationParam.DaxParam.DateTimeZoneParam.DbParam"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "ServerName",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "My Server",
        "expression": "\"pbiotestdb.database.windows.net\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m"
      },
      {
        "name": "MaxId",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Number"
          }
        ],
        "expression": "10000 meta [IsParameterQuery=true, Type=\"Number\", IsParameterQueryRequired=true]",
        "kind": "m"
      },
      {
        "name": "BinParam",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"ggt%423$$57%dfdfcdfhdh\" meta [IsParameterQuery=true, Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m"
      },
      {
        "name": "AnyParam",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"uu63\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m"
      },
      {
        "name": "DateParam",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ],
        "expression": "#datetime(2002, 2, 8, 0, 0, 0) meta [IsParameterQuery=true, List={#datetime(2000, 1, 1, 0, 0, 0), #datetime(2002, 2, 8, 0, 0, 0), #datetime(2003, 12, 8, 0, 0, 0), #datetime(2007, 7, 9, 0, 0, 0)}, DefaultValue=#datetime(2000, 1, 1, 0, 0, 0), Type=\"DateTime\", IsParameterQueryRequired=true]",
        "kind": "m"
      },
      {
        "name": "StrParam",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"Hello\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=false]",
        "kind": "m"
      },
      {
        "name": "BoolParam",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Logical"
          }
        ],
        "expression": "true meta [IsParameterQuery=true, List={true, false}, DefaultValue=true, Type=\"Logical\", IsParameterQueryRequired=true]",
        "kind": "m"
      },
      {
        "name": "DbParam",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"Refresh\" meta [IsParameterQuery=true, List={\"Refresh\", \"test\"}, DefaultValue=\"Refresh\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m"
      }
    ],
    "relationships": [
      {
        "name": "5320f873-fb34-46ef-9610-94df46fe2393",
        "fromColumn": "DateTimeZoneParam",
        "fromTable": "DateTimeZoneParam",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_88018f0e-b9a3-44b1-89a2-45c76066aa00"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_a19a89be-af15-4da0-b678-b32af658ca6a",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "ordinal": 3
              }
            ]
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "partitions": [
          {
            "name": "DateTableTemplate_a19a89be-af15-4da0-b678-b32af658ca6a-fb7ae29d-aff7-42ad-a50f-ef119d8d7457",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Table1NoParams",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3f01ec00-696a-4c8d-9865-2bf13181fc41"
          },
          {
            "name": "LinkedQueryName",
            "value": "Table1NoParams"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "asasasas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "asasasas"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ],
            "dataType": "string",
            "sourceColumn": "asasasas",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Table1NoParams-624d8931-c0bd-4393-bb5f-6bed2f9e6f1c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"pbiotestdb.database.windows.net\", \"Refresh\"),",
                "    dbo_Table1 = Source{[Schema=\"dbo\",Item=\"Table1\"]}[Data]",
                "in",
                "    dbo_Table1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "RefreshConnections_V0",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c11d9409-30ec-481a-92fe-783703dbd7ed"
          },
          {
            "name": "LinkedQueryName",
            "value": "RefreshConnections_V0"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "sourceColumn": "Id",
            "summarizeBy": "count"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ],
            "dataType": "string",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "OriginalConnectionString",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "OriginalConnectionString"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ],
            "dataType": "string",
            "sourceColumn": "OriginalConnectionString",
            "summarizeBy": "none"
          },
          {
            "name": "ConnectionString",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "ConnectionString"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ],
            "dataType": "string",
            "sourceColumn": "ConnectionString",
            "summarizeBy": "none"
          },
          {
            "name": "Provider",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Provider"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ],
            "dataType": "string",
            "sourceColumn": "Provider",
            "summarizeBy": "none"
          },
          {
            "name": "DMGatewayType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "DMGatewayType"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "sourceColumn": "DMGatewayType",
            "summarizeBy": "sum"
          },
          {
            "name": "OnPremGatewayRequired",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Boolean#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "OnPremGatewayRequired"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "sourceColumn": "OnPremGatewayRequired",
            "summarizeBy": "none"
          },
          {
            "name": "IsDMValidated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Boolean#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "IsDMValidated"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "sourceColumn": "IsDMValidated",
            "summarizeBy": "none"
          },
          {
            "name": "Model_Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Model_Id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "sourceColumn": "Model_Id",
            "summarizeBy": "count"
          },
          {
            "name": "DMMoniker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "DMMoniker"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ],
            "dataType": "string",
            "sourceColumn": "DMMoniker",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "RefreshConnections_V0-dc268e63-a9d8-45e3-afc6-7d9b5992c1be",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(ServerName, \"Refresh\"),",
                "    dbo_RefreshConnections_V0 = Source{[Schema=\"dbo\",Item=\"RefreshConnections_V0\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_RefreshConnections_V0, each [ConnectionString] <> AnyParam),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Filtered Rows\", each [OnPremGatewayRequired] = BoolParam),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Filtered Rows1\", each [DMGatewayType] < MaxId)",
                "in",
                "    #\"Filtered Rows2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DaxParam",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "65857814-3499-4846-9f2b-2650cd5ac437"
          },
          {
            "name": "LinkedQueryName",
            "value": "DaxParam"
          },
          {
            "name": "PBI_ResultType",
            "value": "Number"
          }
        ],
        "columns": [
          {
            "name": "DaxParam",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "DaxParam"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ],
            "dataType": "double",
            "sourceColumn": "DaxParam",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "DaxParam-cda693a7-ffef-456f-ae20-273d06f09234",
            "mode": "import",
            "source": {
              "expression": "66 meta [IsParameterQuery=true, Type=\"Number\", IsParameterQueryRequired=true]",
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DurationParam",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0dcab826-d168-4026-8748-fe10cb497423"
          },
          {
            "name": "LinkedQueryName",
            "value": "DurationParam"
          },
          {
            "name": "PBI_ResultType",
            "value": "Duration"
          }
        ],
        "columns": [
          {
            "name": "DurationParam",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "DurationParam"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ],
            "dataType": "double",
            "sourceColumn": "DurationParam",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "DurationParam-dc826333-3f31-46e7-bf86-34e6df3a31be",
            "mode": "import",
            "source": {
              "expression": "#duration(12, 0, 0, 0) meta [IsParameterQuery=true, List={#duration(55, 0, 0, 0), #duration(789, 0, 0, 0), #duration(12, 0, 0, 0)}, DefaultValue=#duration(55, 0, 0, 0), Type=\"Duration\", IsParameterQueryRequired=true]",
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTimeZoneParam",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e958cdab-3485-4ee2-a17b-40d55f49999c"
          },
          {
            "name": "LinkedQueryName",
            "value": "DateTimeZoneParam"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTimeZone"
          }
        ],
        "columns": [
          {
            "name": "DateTimeZoneParam",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "DateTimeZoneParam"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "sourceColumn": "DateTimeZoneParam",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_88018f0e-b9a3-44b1-89a2-45c76066aa00"
                },
                "isDefault": true,
                "relationship": "5320f873-fb34-46ef-9610-94df46fe2393"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTimeZoneParam-c3f26d5e-6bbd-4952-bab9-3c34f10885b6",
            "mode": "import",
            "source": {
              "expression": "#datetimezone(1955, 2, 20, 22, 19, 38, -8, 0) meta [IsParameterQuery=true, Type=\"DateTimeZone\", IsParameterQueryRequired=true]",
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_88018f0e-b9a3-44b1-89a2-45c76066aa00",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "ordinal": 3
              }
            ]
          }
        ],
        "isHidden": true,
        "partitions": [
          {
            "name": "LocalDateTable_88018f0e-b9a3-44b1-89a2-45c76066aa00-7aaf9915-f8e8-46a4-9897-2200ba94e12f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DateTimeZoneParam'[DateTimeZoneParam])), 1, 1), Date(Year(MAX('DateTimeZoneParam'[DateTimeZoneParam])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}